export enum ActionType {
  SIGN_IN = '로그인 요청',
  SIGN_OUT = '로그아웃',
  UPDATE_KILLED_COUNT = '유저 스코어 업데이트',
  UPDATE_VICTIMS = '죽인 범죄자 목록 업데이트',
  ADD_USER_POSTING = '유저 게시물 상태 추가',
  DELETE_USER_POSTING = '유저 게시물 상태 제거',
  FETCH_RANKING = '랭킹 데이터 읽기 요청',
  FETCH_RANKING_SUCCESS = '랭킹 데이터 읽기 성공',
  FETCH_RANKING_FAILURE = '랭킹 데이터 읽기 실패',
  FETCH_COMMUNITY = '게시물 데이터 읽기 요청',
  FETCH_COMMUNITY_SUCCESS = '게시물 데이터 읽기 성공',
  FETCH_COMMUNITY_FAILURE = '게시물 데이터 읽기 실패',
  ADD_POST = '게시물 작성',
  DELETE_POST = '게시물 삭제',
}
